version: 0.0
os: linux
files:
  - source: target/devops-demo-0.0.1-SNAPSHOT.jar
    destination: /home/ec2-user/app
hooks:
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ec2-user
